spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mingletrade
    username: postgres
    password: postgres

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.mingletrade.mingletrade
  configuration:
    map-underscore-to-camel-case: true
