spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mingletrade
    username: postgres
    password: postgres

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

  config:
    import: optional:file:.env[.properties]


aws:
  s3:
    bucket: ${S3_BUCKET}
  region: ${AWS_REGION}
  access-key: ${AWS_ACCESS_KEY_ID}
  secret-key: ${AWS_SECRET_ACCESS_KEY}
  cloudfront-domail: ${CLOUDFRONT_DOMAIN}


mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.mingletrade.mingletrade
  configuration:
    map-underscore-to-camel-case: true

